### PR TITLE
Version Mismatch Errors Fixed

### PR DESCRIPTION
**Pull request by cosmic-heart**
Fixed Version mismatches, Code upgrades.

1) added version to the requirements.txt file. The particular version supports inference and training. 
2) Changed SuperMarioBros-v0 to SuperMarioBros-v3.
3) q.load_state_dict(torch.load(ckpt_path, map_location=torch.device(device))). The state_dict() can be loaded to the device directly.

### CODE REVIEW

**Comment by jiseongHAN** [comment]
Hello! Thanks for fixing version specifically!
I think it is better not to change hyperparameters (memory size, num_episodes) and gym env version.
(I know it would be better to use SuperMarioBros-v3, but I just want to keep consistency on my work.)

If you don't mind, I will commit on this branch with prev-hyperparams and gym env version and merge!

**Comment by cosmic-heart** [comment]
yeah sure, actually for testing I changed the hyper parameters and forgot to change it back.

**Comment by cosmic-heart** [comment]
It seems, q_target.pth model is overridden by my model. Actually i just tried for 5 episodes. Get back 39th commit model (your model)

**Comment by cosmic-heart** [comment]
And the q_target.pth in 39th commit having EOF file error. This Model size is 2MB (approx) but it should be 41 MB (approx). So there is mismatch is the state_dict() size.

**Pull request merged**
